### PR TITLE
Exclude huge and unnecessary venv*/ from dist

### PR DESCRIPTION
**Pull request by carver**
See an example issue here:
https://github.com/ethereum/eth-account/issues/150

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Review by kclowes — APPROVED** [review]
That photo 😆 LGTM! 

I'm not sure where this should go, but it's also worth noting that if a release has already been done with the `venv`s bundled, if that same person is doing the release, the `venv/` directories need to be deleted from the local file system in order for them to be excluded in the next release. Maybe that comment belongs in the `cutting-a-release-document`?

**Comment by carver** [comment]
> Maybe that comment belongs in the `cutting-a-release-document`?

Yeah, or maybe we could update the `Makefile` to be sure that old build files are cleaned before every build? Frankly, I was assuming that was the default already.

**Comment by carver** [comment]
Where is the venv/ that needs to be manually deleted? I would have assumed these lines would take care of everything:
https://github.com/ethereum/ethereum-python-project-template/blob/b88fcf3c0b70ea7e4bd0fbc89b546a37877ce50e/Makefile#L19-L22

**Comment by kclowes** [comment]
They live in the root. I think the problem with removing them on the `clean-build` step is that you need to be in a virtualenv to release. I may be wrong on that though or releasing wrong.

**Comment by carver** [comment]
> They live in the root. I think the problem with removing them on the `clean-build` step is that you need to be in a virtualenv to release. I may be wrong on that though or releasing wrong.

Oh, you didn't have to clear a copied artifact, you had to delete your actual virtualenv? That's ugly

**Comment by kclowes** [comment]
yeah, super ugly. The manifest change should work now for virtualenvs in the future. But I think because a virtualenv was already packaged with the same name, it was getting included even after I added the Manifest change. I had to rename my local virtualenv which fixed the issue.

**Comment by carver** [comment]
> But I think because a venv dir was already packaged with the same name, it was getting included even after I added the Manifest change

This is the part that doesn't make sense to me. If the build/ and dist/ are removed, how does it even know what was packaged last time?

**Comment by kclowes** [comment]
> This is the part that doesn't make sense to me. If the build/ and dist/ are removed, how does it even know what was packaged last time?

I'm not sure, I assumed something was caching. Could also be a PEBCAK sort of problem :)

**Comment by carver** [comment]
> > This is the part that doesn't make sense to me. If the build/ and dist/ are removed, how does it even know what was packaged last time?
> 
> I'm not sure, I assumed something was caching. Could also be a PEBCAK sort of problem :)

Haha, sure, just seems like something worth digging into understanding.

It should be possible to confirm by cycling between `make clean` and `python setup.py sdist bdist_wheel`, and inspecting the packaged `.tar.gz`. It sucks to debug when the test cycle is once every release! :)

**Comment by kclowes** [comment]
The plot thickens! This `recursive-exclude` line is actually not doing what I thought it was doing. When running `make dist` in my local `eth-account` dir, it's not respecting the recursive-exclude line in `Manifest.in` for the `venv*` directories. And I also remembered how I reached the conclusion about needing to change the name of the venv. There is a line in the output of `make dist` that says:
```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no previously-included files matching 'venv*' found under directory '*'
```

So, I think this line should changed to `prune venv*`. It looks like locally that does the trick for me consistently. See: https://github.com/ethereum/eth-account/pull/165

**Comment by carver** [comment]
Cool, `prune` seems like a solid choice. The thing I don't get is: wouldn't this have the same problem, of including the `__pycache__` directories from the root in the final distribution?

**Comment by carver** [comment]
> _I believe_ because of the `make clean-pyc` that gets run.

Oh yeah, that makes sense.

**Comment by carver** [comment]
Ok, well I'm good merging this in as a clear improvement at this point 👍🏻

**Pull request merged**
